# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/GIT/ESiF_Zynq/Task2/ESiF_Task2/ESiF_Task2.srcs/sources_1/bd/zynq/ip/zynq_axi_gpio_0_6/zynq_axi_gpio_0_6.xci
# IP: The module: 'zynq_axi_gpio_0_6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/GIT/ESiF_Zynq/Task2/ESiF_Task2/ESiF_Task2.srcs/sources_1/bd/zynq/ip/zynq_axi_gpio_0_6/zynq_axi_gpio_0_6_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_axi_gpio_0_6'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/GIT/ESiF_Zynq/Task2/ESiF_Task2/ESiF_Task2.srcs/sources_1/bd/zynq/ip/zynq_axi_gpio_0_6/zynq_axi_gpio_0_6_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_axi_gpio_0_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/GIT/ESiF_Zynq/Task2/ESiF_Task2/ESiF_Task2.srcs/sources_1/bd/zynq/ip/zynq_axi_gpio_0_6/zynq_axi_gpio_0_6.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_axi_gpio_0_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/GIT/ESiF_Zynq/Task2/ESiF_Task2/ESiF_Task2.srcs/sources_1/bd/zynq/ip/zynq_axi_gpio_0_6/zynq_axi_gpio_0_6.xci
# IP: The module: 'zynq_axi_gpio_0_6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/GIT/ESiF_Zynq/Task2/ESiF_Task2/ESiF_Task2.srcs/sources_1/bd/zynq/ip/zynq_axi_gpio_0_6/zynq_axi_gpio_0_6_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_axi_gpio_0_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/GIT/ESiF_Zynq/Task2/ESiF_Task2/ESiF_Task2.srcs/sources_1/bd/zynq/ip/zynq_axi_gpio_0_6/zynq_axi_gpio_0_6_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_axi_gpio_0_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/GIT/ESiF_Zynq/Task2/ESiF_Task2/ESiF_Task2.srcs/sources_1/bd/zynq/ip/zynq_axi_gpio_0_6/zynq_axi_gpio_0_6.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_axi_gpio_0_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
