# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/GIT/ESiF_Zynq/Task2/ESiF_Task2/ESiF_Task2.srcs/sources_1/bd/zynq/ip/zynq_rst_ps7_0_100M_3/zynq_rst_ps7_0_100M_3.xci
# IP: The module: 'zynq_rst_ps7_0_100M_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/GIT/ESiF_Zynq/Task2/ESiF_Task2/ESiF_Task2.srcs/sources_1/bd/zynq/ip/zynq_rst_ps7_0_100M_3/zynq_rst_ps7_0_100M_3_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_rst_ps7_0_100M_3'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/GIT/ESiF_Zynq/Task2/ESiF_Task2/ESiF_Task2.srcs/sources_1/bd/zynq/ip/zynq_rst_ps7_0_100M_3/zynq_rst_ps7_0_100M_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_rst_ps7_0_100M_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/GIT/ESiF_Zynq/Task2/ESiF_Task2/ESiF_Task2.srcs/sources_1/bd/zynq/ip/zynq_rst_ps7_0_100M_3/zynq_rst_ps7_0_100M_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_rst_ps7_0_100M_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/GIT/ESiF_Zynq/Task2/ESiF_Task2/ESiF_Task2.srcs/sources_1/bd/zynq/ip/zynq_rst_ps7_0_100M_3/zynq_rst_ps7_0_100M_3.xci
# IP: The module: 'zynq_rst_ps7_0_100M_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/GIT/ESiF_Zynq/Task2/ESiF_Task2/ESiF_Task2.srcs/sources_1/bd/zynq/ip/zynq_rst_ps7_0_100M_3/zynq_rst_ps7_0_100M_3_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_rst_ps7_0_100M_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/GIT/ESiF_Zynq/Task2/ESiF_Task2/ESiF_Task2.srcs/sources_1/bd/zynq/ip/zynq_rst_ps7_0_100M_3/zynq_rst_ps7_0_100M_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_rst_ps7_0_100M_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/GIT/ESiF_Zynq/Task2/ESiF_Task2/ESiF_Task2.srcs/sources_1/bd/zynq/ip/zynq_rst_ps7_0_100M_3/zynq_rst_ps7_0_100M_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_rst_ps7_0_100M_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
